CREATE TABLE "Users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(255) NOT NULL,
  "profile_name" varchar(255) NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "UserAuth" (
  "user_id" int PRIMARY KEY,
  "username" varchar(255) NOT NULL,
  "password_hash" varchar(512) NOT NULL,
  "salt" varchar(255) NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "Topics" (
  "topic_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "topic_name" varchar(255) NOT NULL,
  "user_id" int NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "Sets" (
  "set_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "set_name" varchar(255) NOT NULL,
  "topic_id" int NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "Fields" (
  "field_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "field_name" varchar(255) NOT NULL,
  "field_type" varchar(255) NOT NULL,
  "set_id" int NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "Words" (
  "word_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "word_name" varchar(255) NOT NULL,
  "set_id" int NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "FieldData" (
  "word_id" int NOT NULL,
  "field_id" int NOT NULL,
  "field_value" text,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

ALTER TABLE "UserAuth" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Topics" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Sets" ADD FOREIGN KEY ("topic_id") REFERENCES "Topics" ("topic_id");

ALTER TABLE "Fields" ADD FOREIGN KEY ("set_id") REFERENCES "Sets" ("set_id");

ALTER TABLE "Words" ADD FOREIGN KEY ("set_id") REFERENCES "Sets" ("set_id");

ALTER TABLE "FieldData" ADD FOREIGN KEY ("word_id") REFERENCES "Words" ("word_id");

ALTER TABLE "FieldData" ADD FOREIGN KEY ("field_id") REFERENCES "Fields" ("field_id");
